Dev/milestone2 docs
ThalesGroup/hydrator-plugins pull request #157
Opened 2020-01-13 05:16 UTC by lav-mudgal-guavus

2020-01-13 06:40 UTC, lav-mudgal-guavus commented on core-plugins/docs/FileDelete-action.md
> +File Delete is a Guavus Enterprise Accelerator that is used to delete a file or files.
This is an open source plugin.

2020-01-13 06:40 UTC, lav-mudgal-guavus commented on core-plugins/docs/FileMove-action.md
> +File Move is a Guavus Enterprise Accelerator that is used to moves a file or files.
This is an open source plugin.

2020-01-13 06:51 UTC, lav-mudgal-guavus commented on core-plugins/docs/FileMove-action.md
> +**continueOnError:** To specify if the pipeline should continue if the move process fails. If all files are not successfully moved, the action will not return the files already moved to their origina
"revert" instead of "return" ?

2020-01-13 06:54 UTC, lav-mudgal-guavus commented on transform-plugins/docs/XMLMultiParser-transform.md
> +XML Multi Parser is a Guavus Enterprise Accelerator that uses XPath to extract fields from an XML document. It will generate records from the children of the element specified by the XPath.
this is an open source plugin.

2020-01-13 07:05 UTC, lav-mudgal-guavus commented on transform-plugins/docs/XMLMultiParser-transform.md
>  Conditions
we should change this to Note or something similar

2020-01-13 07:17 UTC, rohit-raina-guavus commented on core-plugins/docs/FileMove-action.md
> +**continueOnError:** To specify if the pipeline should continue if the move process fails. If all files are not successfully moved, the action will not return the files already moved to their origina
"restore"

2020-01-13 07:19 UTC, deepak-maheshwari-ext requested changes

2020-01-13 07:19 UTC, deepak-maheshwari-ext commented on core-plugins/docs/XMLReader-batchsource.md
> +XML Reader is a Guavus Enterprise Accelerator that allows users to read XML files stored on HDFS.
this is not "Guavus Enterprise Accelerator" . it is an "open source accelerator" .

2020-01-13 07:19 UTC, deepak-maheshwari-ext commented on database-plugins/docs/Database-batchsource.md
> +Database is a Guavus Enterprise Accelerator that is used to read from a database using a configurable SQL query. It outputs one record for each row returned by the query.
this is not "Guavus Enterprise Accelerator" . it is an "open source accelerator" .

2020-01-13 07:19 UTC, deepak-maheshwari-ext commented on database-plugins/docs/Database-batchsource.md
> +Consider a scenario wherein you want to create daily snapshots of a database table by using this source and writing to a TimePartitionedFileSet. This can be achieved by configuring the accelerator as
"create daily snapshots of a database table by" -> "read data from database"

2020-01-13 07:19 UTC, deepak-maheshwari-ext commented on transform-plugins/docs/JSONParser-transform.md
> +JSON Parser is a Guavus Enterprise Accelerator that parses an input JSON event into a record. The input JSON event can either map string fields to values or it can be a complex nested JSON structure.
it is an "ope source accelerator"

2020-01-13 07:19 UTC, deepak-maheshwari-ext commented on transform-plugins/docs/JSONParser-transform.md
> +The functions perform aggregations at the tail end of the path. The functions take the output of the expression as input for performing aggregations. The aggregation function \\\\\\\\\\\\\\\\\\\\\\\\
please remove these \'s

2020-01-13 07:19 UTC, deepak-maheshwari-ext commented on transform-plugins/docs/Normalize-transform.md
> +Normalize is a Guavus Enterprise Accelerator that is used to break one source row into multiple target rows.
it is an "open source Accelerator".

2020-01-13 07:55 UTC, lav-mudgal-guavus commented on transform-plugins/docs/XMLToJSON-transform.md
> +# XML to JSON
# XML to JSON Converter

2020-01-13 07:56 UTC, lav-mudgal-guavus commented on transform-plugins/docs/XMLToJSON-transform.md
> +XML to JSON accepts a field containing a properly-formatted XML string and converts it into a properly-formatted JSON string.
"XML to JSON converter" accelerator accepts a field..

2020-01-13 07:57 UTC, lav-mudgal-guavus commented on transform-plugins/docs/XMLToJSON-transform.md
> +XML to JSON can be used with the Javascript transform for the parsing of complex XML documents into parts. Once the XML is a JSON string, you can convert it into a Javascript object using:
This accelerator can be used with

2020-01-14 04:49 UTC, neelesh-nirmal approved these changes
LGTM

2020-01-14 04:49 UTC, neelesh-nirmal commented on transform-plugins/docs/JSONFormatter-transform.md
> +JSON Formatter is a Guavus Enterprise Accelerator that formats a Structured Record as JSON Object. This accelerator is used to convert the Structured Record to a JSON object and write to the output r
This is an open source plugin

2020-01-14 04:49 UTC, neelesh-nirmal commented on transform-plugins/docs/CSVFormatter-transform.md
> +CSV Formatter is a Guavus Enterprise Accelerator that formats a Structured Record as a CSV Record.
This is an open source plugin.

2020-01-14 04:49 UTC, neelesh-nirmal commented on transform-plugins/docs/Encryptor-transform.md
> +# Field Encryptor
👍

2020-01-14 04:49 UTC, neelesh-nirmal commented on transform-plugins/docs/Encryptor-transform.md
> +Field Encryptor is a Guavus Enterprise Accelerator that is used to encrypt the fields present in the input records using a java keystore, which must be present on all nodes of the cluster.
This is an open source plugin.

2020-01-14 12:02 UTC, deepak-maheshwari-ext approved these changes
LGTM

2020-01-14 12:02 UTC, merged